### ISSUE TITLE
Required nodes

### ISSUE THREAD

**Issue by ghost** [geraintluff/json-schema-compatibility#4]
I see your tool drops them entirely, any chance conversion will be supported? Or is this a hard problem or out of scope?

https://github.com/json-schema/json-schema/wiki/ChangeLog#required

For the rest, works great. My RAML schemas are v3 and using this tool, and of course deletion of the `$schema` key, works great feeding it to `json-schema-faker` as v4, just this was one of the things missing, `required` properties.

**Comment by ghost** [comment]
I guess this topic I just found answers it: http://grokbase.com/t/gg/json-schema/157w8sphbg/converting-from-draft3-to-draft4-what-to-do-with-required-outside-of-properties

I'll just close this for now

**Comment by geraintluff** [comment]
It should correctly convert `required` that are within other schemas, shown in this test: https://github.com/geraintluff/json-schema-compatibility/blob/master/test/01%20-%20Keyword%20fixes/01%20-%20Required.js#L6-L46

What issue were you seeing?
